experiment_metadata:
  model_version: "gemma-2-0.3B"
  method: "MaxEnt"
  noise_config: "global"
  beta: 0.1
  seed: 111
  alphas: [0.55, 0.65, 0.7, 0.75]
  relearn_lrs: [ 1e-3, 7e-4, 4e-4, 1e-4, 7e-5, 5e-5, 1e-5, 7e-6, 4e-6, 1e-6 ]
  include_baselines: true
  first_train_file: "pretrain/train_multiplication_division.jsonl"
  second_train_file: null
  interleave_probs: [ 1.0 ]
  wandb_project: "relearn_attack_only_forget_data"

baselines_library:
  gemma-2-0.3B:
    - "pretrained_models/gemma-2-0.3B_addition_subtraction+eng"
    - "unlearned_models/MaxEnt/pretrained_models_gemma-2-0.3B_all_arithmetic+eng_final_model_lr_1.0e-04"
  gemma-2-0.1B:
    - "pretrained_models/gemma-2-0.1B_addition_subtraction+eng"
    - "unlearned_models/MaxEnt/pretrained_models_gemma-2-0.1B_all_arithmetic+eng_final_model_lr_8.0e-05"

default_config:
  seed: 42
  batch_size: 3
  gradient_accumulation_steps: 5
  epochs: 1
  max_steps: 500
  num_warmup_steps: 1
  validation_steps: 5
  save_checkpoint_steps: 999
  scheduler_type: "cosine"
  weight_decay: 0.0
  gradient_clipping_threshold: 1.0
  max_length: 256
  join_or_subsequence: true
  use_wandb: true
  use_local_record: true
  save_models: false
  device: "cuda"