default_config:
  seed: 42
  device: "cuda"
  epochs: 1
  max_steps: 10
  num_warmup_steps: 0
  validation_steps: 1
  save_checkpoint_steps: -1
  scheduler_type: "cosine"
  weight_decay: 0.0
  gradient_clipping_threshold: 1.0
  max_length: 256
  use_wandb: true
  use_local_record: true
  forget_rel_path: "pretrain/train_multiplication_division.jsonl"
  retain_rel_path: "pretrain/train_addition_subtraction.jsonl"
  valid_rel_path: "pretrain/valid_eng.jsonl"

lr_ranges:
  MaxEnt: [6e-5, 7e-5, 8e-5, 9e-5, 1e-4, 2e-4, 3e-4, 4e-4]

setups:
  gemma-2-0.1B_MaxEnt:
    method: "MaxEnt"
    use_retain: true
    batch_size: 4
    gradient_accumulation_steps: 10
    min_lr: 0.00004
    wandb_project: "gemma-2-0.1B_all_arithmetic+eng_unlearn_MaxEnt"
    model_rel_path: "pretrained_models/gemma-2-0.1B_all_arithmetic+eng/final_model"